version: '3'
services:
  app:
    image: golang:1.19.0-buster
    build: ./api
    container_name: qr-api
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
    tty: true # コンテナの永続化
    depends_on:
      - "db"
    command: "./start.sh"
  db:
    image: mysql:8.0.21
    container_name: qr-db
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'sample_db'
    platform: linux/x86_64
volumes:
  go_path:
